---
- name: Create directories for templated files.
  include_tasks:
    file: createdir.yml
    apply:
      become: true
  vars:
    dir: "{{ item }}"
  when: item.state == "directory"
  with_filetree: "{{ path if path is defined and path != None else [] }}"

- name: Template files.
  template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | replace('__HOME__', ansible_env.HOME) | ltrim('/') }}"
    mode: "{{ item.mode }}"
    owner: "{{ ansible_env.USER if '__HOME__' in item.path else 'root' }}"
  become: true
  with_filetree: "{{ path }}"
  when: path != None and item.state == "file" and item.path|basename != ".DS_Store"
